### ISSUE TITLE
Reporting warnings as an error

### ISSUE THREAD

**Issue by avdi** [brandoncc/vscode-seeing-is-believing#6]
Currently the seeing_is_believing gem is emitting some deprecation warnings from the `tree_rewriter` gem:

```
/usr/local/bundle/gems/parser-2.5.3.0/lib/parser/source/tree_rewriter.rb:269: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/bundle/gems/parser-2.5.3.0/lib/parser/source/tree_rewriter/action.rb:16: warning: The called method `initialize' is defined here
```

This extension seems to be interpreting those as errors (even though exit status is 0):

![image](https://user-images.githubusercontent.com/982/76557680-61ea0f00-6472-11ea-973b-09116d5e92d5.png)

As a result, the file isn't updated with expression results.

**Comment by brandoncc** [comment]
I just saw this myself yesterday. Thanks for creating an issue on it @avdi. I'll take a look at it this week.

**Comment by brandoncc** [comment]
@avdi it looks like if I don't use `--xmpfilter-style`, it will work again. I'd prefer not to do that, so we'll see if Josh responds on the [open issue](https://github.com/JoshCheek/seeing_is_believing/issues/155) in the near future.

If I have to, I will alter the arguments (or make them more configurable so that xmpfilter-style can still be used pre-2.7.0).

Thanks for using (or at least checking out) my extension, its an honor sir!

**Comment by brandoncc** [comment]
@avdi I just checked and you can do [this](https://github.com/brandoncc/vscode-seeing-is-believing#features) as a hack to get it working. I will address the actual problem in the near future though.

**Comment by brandoncc** [comment]
I just published a new version with an option to allow continuing to run even when stderr is not empty. Take a look [here](https://github.com/brandoncc/vscode-seeing-is-believing#known-issues), and let me know if it doesn't help you.

Thanks again for opening this issue.

**Comment by brandoncc** [comment]
Josh resolved the issue in version 4 of his gem, which I just tested and verified.
